### ISSUE TITLE
Getting error in build for iOS - IDFADelegate

### ISSUE THREAD

**Issue by nirmal-mobiquity** [Appboy/appboy-cordova-sdk#52] opened 2020-04-23 14:51 UTC
We are getting below error.

`Plugins/cordova-plugin-appboy/IDFADelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

**Comment by Bucimis** [comment] 2020-04-23 15:06
@nirmal-mobiquity could you post a bit more detail from the logs? What about `IDFADelegate` is causing the build to fail?

**Comment by nirmal-mobiquity** [comment] 2020-04-23 15:10
yes

`
The following build commands failed:
	CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/Mo-bgjxglqgcrdhlcalq/Build/Intedfrmediates.noindex/Mo.build/Debug-iphonesimulator/Mo.build/Objects-normal/x86_64/IDFADelegate.o /Users/jenkins/workspace/Mo/app/dev/frontend-ios/platforms/ios/Mo/Plugins/cordova-plugin-appboy/IDFADelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Command finished with error code 65: xcodebuild -workspace,Mo.xcworkspace,-scheme,Mo,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/jenkins/workspace/Mo/app/dev/frontend-ios/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/jenkins/workspace/Mo/app/dev/frontend-ios/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/jenkins/workspace/Mo/app/dev/frontend-ios/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[ERROR] An error occurred while running subprocess cordova.
`

**Comment by radixdev** [comment] 2020-04-23 17:38
Hi @nirmal-mobiquity 

We have reverted the plugin.xml tag back to using framework for iOS. Please let us know if 2.14.0 fixes your issue.

**Comment by nirmal-mobiquity** [comment] 2020-04-24 13:53
@radixdev I changed it to version 2.11.2 as well but still issue seems persists.

can you use any certificate with disabling in-app purchase and try at your end.

 cc : @Bucimis

**Comment by Bucimis** [comment] 2020-09-17 01:57
Hi @nirmal-mobiquity, did 2.14.0 fix your issue?

**Comment by radixdev** [comment] 2020-10-23 15:56
Hey @nirmal-mobiquity ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Comment by danielraban** [comment] 2020-12-15 17:17
@nirmal-mobiquity did you find a fix for this? i am having the same issue

**Comment by Bucimis** [comment] 2020-12-15 17:19
@danielraban thanks for getting in touch! Could you be more specific about which issue you're experiencing (xcode error, IAP auto-add issue, etc)?

**Comment by danielraban** [comment] 2020-12-15 17:46
@Bucimis 
running `ionic cordova build ios` produces

```** ARCHIVE FAILED **

Command finished with error code 65: xcodebuild -workspace,Panda.xcworkspace,-scheme,Panda,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,Panda.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/user/hathway/panda-ui/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/user/hathway/panda-ui/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/user/hathway/panda-ui/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess cordova.

        cordova build ios --verbose exited with exit code 65.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 65) +27ms
error Command failed with exit code 65.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by danielraban** [comment] 2020-12-15 17:50
@Bucimis 
running `cordova build ios` produces 
```** BUILD FAILED **


The following build commands failed:
	CompileC /Users/user/Library/Developer/Xcode/DerivedData/Panda-fxbgdyqqvfwighamjjjqkirwzpya/Build/Intermediates.noindex/Panda.build/Debug-iphonesimulator/Panda.build/Objects-normal/x86_64/IDFADelegate.o /Users/user/hathway/panda-ui/platforms/ios/Panda/Plugins/cordova-plugin-appboy/IDFADelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Command finished with error code 65: xcodebuild -workspace,Panda.xcworkspace,-scheme,Panda,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 12 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/user/hathway/panda-ui/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/user/hathway/panda-ui/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/user/hathway/panda-ui/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess cordova.

        cordova build ios --verbose exited with exit code 65.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 65) +36ms
error Command failed with exit code 65.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Bucimis** [comment] 2020-12-15 23:07
@danielraban 
1) Which version of the Cordova SDK and Braze native iOS SDK are you using?
2) Do you have `enableIDFACollection` turned on?
3) Are you able to compile the project in XCode directly? If not, what error do you see there?

**Comment by nirmal-mobiquity** [comment] 2020-12-16 05:44
so  @Bucimis we  are able to   do build with  xcode by doing change
in  setting  change to legacy build and in pods  of appboy  change enable_bitcode value to false.

It  doesn't work with terminal commands and  we are not able to use CICD tools.

cc : @danielraban

**Comment by danielraban** [comment] 2020-12-17 17:41
@Bucimis 
1. I am using
```Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 18 other plugins)```
 2. How can I check this in cordova?
 3. I am able to compile in xcode make the change @nirmal-mobiquity suggested. but as they have stated we need this for pipeline

**Comment by danielraban** [comment] 2020-12-21 20:42
@Bucimis is there any update on this?

**Comment by tbelote** [comment] 2020-12-21 20:53
Here is a sample ionic Cordova app I can build from cli, can you provide an example or instructions to reproduce the error? https://github.com/tbelote/myApp

**Comment by danielraban** [comment] 2020-12-21 21:25
@tbelote I was unable to get your app to build locally would you mind outputting `ionic info` and `node -v` also which version of xcode are you on? 

Mine is as follows: 
```Ionic:

   Ionic CLI                     : 6.12.3 (/Users/user/.nvm/versions/node/v14.15.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.15.2
   native-run  : 1.3.0

System:

   ios-deploy : 1.11.3
   ios-sim    : 8.0.2
   NodeJS     : v14.15.3 (/Users/user/.nvm/versions/node/v14.15.3/bin/node)
   npm        : 6.14.9
   OS         : macOS Catalina
   Xcode      : Xcode 12.3 Build version 12C33
```

```node -v v14.15.3```

The steps to reproduce this inside out our app are: 
1. `cordova plugin add https://github.com/appboy/appboy-cordova-sdk#master`
2. `ionic cordova platform rm ios`
3. add preferences to the config.xml described here https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup/#step-1-get-the-sdk
4. `ionic cordova platform add ios`
5. run `ionic cordova build ios`

**Comment by tbelote** [comment] 2020-12-22 00:47
```
% ionic info  

Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/thomas.belote/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.7
   OS                : macOS Catalina
   Xcode             : Xcode 12.1 Build version 12A7403


```

**Comment by tbelote** [comment] 2020-12-22 00:47
Oh I wonder if it's Xcode 12.3 I'll check that out.

**Comment by danielraban** [comment] 2020-12-22 03:37
@tbelote I got a success finally, it's an issue with `cordova-plugin-firebasex` once i remove that plugin with `ionic cordova plugin rm cordova-plugin-firebasex` it builds.
cc: @nirmal-mobiquity

**Comment by nirmal-mobiquity** [comment] 2020-12-22 06:03
hey @danielraban  I don't have  firebase plugin. only related plugin i  can think of is google  plus. And It  can not be removed.
@tbelote is it incompatible  with other plugins ?

**Comment by tbelote** [comment] 2020-12-22 13:22
I don't think we expect any incompatibility with other plugins. I'll take a look to see what might be going on.

**Comment by tbelote** [comment] 2020-12-22 14:00
I can reproduce with the Cordova-plugin-firebasex plugin. will try to figure out why.

**Comment by nirmal-mobiquity** [comment] 2020-12-22 14:31
yes @tbelote it  might resolve for us as well.

**Comment by tbelote** [comment] 2020-12-22 16:01
I see the issue is that firebasex converts the cocoapod project to build frameworks instead of static libraries and that's why the header file is no longer found. I'll discuss with the team to see what we can do. If you switch back to static libraries then firebase will fail to build.

**Comment by tbelote** [comment] 2020-12-22 19:42
Ok here is what IDFADelegate.h should look like so that it works with other plugins that turn on use_frameworks! I'll work on putting this in to the next Cordova plugin release, but I don't usually work on that repository so I'm uncertain of the timing of the release. I believe you can manually make this change for now.

`#import <Foundation/Foundation.h>
#if __has_include(<Appboy-iOS-SDK/Appboy_iOS_SDK.framework/Headers/ABKIDFADelegate.h>)
#import <Appboy-iOS-SDK/Appboy_iOS_SDK.framework/Headers/ABKIDFADelegate.h>
#elif __has_include(<ABKIDFADelegate.h>)
#import <ABKIDFADelegate.h>
#else
#import "ABKIDFADelegate.h"
#endif

@interface IDFADelegate : NSObject <ABKIDFADelegate>

@end
`

**Comment by tbelote** [comment] 2020-12-23 01:17
Actually this doesn't explain why some of the header files seem to work without an error. I'll keep looking in to it tomorrow.

**Comment by nirmal-mobiquity** [comment] 2020-12-23 11:12
@tbelote still it didn't resolved. I am  getting below error
```
/Pods-project-frameworks.sh: line 131: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by tbelote** [comment] 2020-12-23 21:06
I discovered this problem applies to more files after deleting derived data. here is my latest attempt at a patch. 
[pod_framework.patch.txt](https://github.com/Appboy/appboy-cordova-sdk/files/5737129/pod_framework.patch.txt)

**Comment by tbelote** [comment] 2020-12-23 21:15
@nirmal-mobiquity can you send me a list of all your plugins so I can make sure there are no other issues? you can email me at thomas.beote@braze.com

**Comment by nirmal-mobiquity** [comment] 2020-12-24 05:40
@tbelote I will  check for patch document if it can help, also I have sent an email with plugins list.

**Comment by Lavanya-BR-Mindtree** [comment] 2020-12-24 06:15
> I discovered this problem applies to more files after deleting derived data. here is my latest attempt at a patch.
> [pod_framework.patch.txt](https://github.com/Appboy/appboy-cordova-sdk/files/5737129/pod_framework.patch.txt)

where do we need to add this patch document?

**Comment by frissonlabs** [comment] 2021-01-05 23:35
Why did this get closed before a solution was provided?

**Comment by Bucimis** [comment] 2021-01-05 23:40
@frissonlabs thanks for the heads up, the issue was originally closed due to inactivity, re-opening now due to more signal

**Comment by danielraban** [comment] 2021-01-08 16:29
are there any updates on this? it is going to become a blocker for multiple clients.

**Comment by hokstuff** [comment] 2021-01-08 16:30
Hi all,

We have worked on creating and verifying a fix and are planning to release it in the coming days. Stay tuned!

**Comment by hokstuff** [comment] 2021-01-08 18:52
Hi @danielraban @frissonlabs @Lavanya-BR-Mindtree @nirmal-mobiquity,

We have just released our [Cordova SDK version 3.21.0](https://github.com/Appboy/appboy-cordova-sdk/releases/tag/2.21.0) that should fix this issue. Please let us know if you have further problems - thank you!

**Closed by hokstuff** 2021-01-08 18:52 UTC

**Comment by nirmal-mobiquity** [comment] 2021-01-13 11:44
Still it failed for me with below error, 1 error is resolved and this error is regarding ENABLE_BITCODE we have to set to false to make build worked.
`ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1200.0.32.28.0_0' Reader: '1103.0.32.62_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.62)' for architecture arm64`

**Comment by nirmal-mobiquity** [comment] 2021-01-19 12:41
@tbelote @hokstuff any update on my above message  ? I am still waiting.

**Comment by hokstuff** [comment] 2021-01-19 16:29
@nirmal-mobiquity What command are you using to build that gives you that error? Which Xcode version are you using? Are you seeing this error on devices as well as simulators?

**Comment by tbelote** [comment] 2021-01-19 23:16
Are you still running Xcode 11? @nirmal-mobiquity ? I think we are building our releases on Xcode 12 now and bitcode would require we use a similar version. Disabling bitcode is also a valid path.

**Comment by nirmal-mobiquity** [comment] 2021-01-20 06:52
Yes we are using 11.3, let me updated xcode and I will reply here in a day or two. But I would suggest add xcode version in prerequisites as well to prevent any confusion.

**Comment by nirmal-mobiquity** [comment] 2021-01-25 10:48
@hokstuff @tbelote 
Issue is resolved after  updating xcode to version 12.3.  Many thanks.

It would be really great if you add support for npm packages as well. I am not sure  if its already in your roadmap. Can  i  create ticket for  that ?

**Comment by Bucimis** [comment] 2021-01-25 15:00
@nirmal-mobiquity opened it here: https://github.com/Appboy/appboy-cordova-sdk/issues/64 feel free to add any extra detail

**Comment by nirmal-mobiquity** [comment] 2021-01-25 15:05
thanks @Bucimis added basic information in ticket, let's move conversation ahead on it. Feel free to connect for any more information.
