### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-cordova-sdk#38] opened 2019-05-14 23:01 UTC
We are receiving app crash reports from some android device users because of following runtime exception.

```java
java.lang.RuntimeException: 
  at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey (SourceFile:206)
  at com.appboy.Appboy.g (SourceFile:1681)
  at com.appboy.Appboy.f (SourceFile:87)
  at com.appboy.Appboy$29.run (SourceFile:277)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```
It looks like [Appboy.configure()](https://github.com/Appboy/appboy-cordova-sdk/blob/master/src/android/AppboyPlugin.java#L134) is not executed for locked class object for some unknown reason.

![appboy_class](https://user-images.githubusercontent.com/13875691/57737592-12c02b80-7661-11e9-90fb-73a2ac9f2d18.png)
  

If I add the api key in appboy.xml as I found the similar issue (https://github.com/Appboy/appboy-segment-android/issues/5), it does not seem to happen.

```xml
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="com_appboy_api_key">xxxxxxxxxxxxxxxxxxxxx</string>
</resources>
```

However, setting the api key to the preference (config.xml) as in the documentation (https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup/#configure-the-plugin) should not have this problem.

**Comment by ronkot** [comment] 2019-05-15 05:59
We're also experiencing this problem when using the config.xml as in documentation. Have not tried yet using appboy.xml, but would definitely like out-of-the-box solution :)

https://github.com/Appboy/appboy-cordova-sdk/issues/37

**Comment by radixdev** [comment] 2019-05-15 21:08
Hi @jamesyoon11 @ronkot ,

This could potentially be a race between `pluginInitialize` and the android lifecycle methods being called out of order. We will do more investigation on our end and will update the SDK if we have a solution.

**Comment by radixdev** [comment] 2019-06-04 18:15
Hi @jamesyoon11 @ronkot ,

A fix was added in SDK 2.10.0. Please let us know if this fixes the api key exceptions you've been seeing.

**Comment by ronkot** [comment] 2019-06-05 06:55
Okay, great! I'll test the new release and report back. This may take some time as we'll get the actual results only after we've released a new version of our app.

**Comment by radixdev** [comment] 2019-09-13 15:33
Hey @ronkot ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Closed by radixdev** 2019-09-13 15:33 UTC

**Comment by ronkot** [comment] 2019-09-16 05:17
Just reaching back to tell that the problem is indeed now fixed. Great work!  👍
